sonar.organization=your-sonarcloud-org
sonar.projectKey=your-sonarcloud-project-key

sonar.sources=backend/src,frontend/src
sonar.tests=backend/src,frontend/src
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts,**/*.e2e-spec.ts
sonar.exclusions=**/node_modules/**,**/dist/**,**/*.module.ts,**/main.ts

sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info
sonar.typescript.lcov.reportPaths=backend/coverage/lcov.info

sonar.sourceEncoding=UTF-8
